{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatewayd.fullname" . }}-monitor
  labels:
    {{- include "gatewayd.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
  selector:
    {{- include "gatewayd.selectorLabels" . | nindent 4 }}
{{- end }}